In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [40]:
df = pd.read_csv('Home_prices.csv')
df

Unnamed: 0  Rooms Type Method  Distance  Bathroom  Car  Landsize  \
0               0      2    h     SS       2.5       1.0  1.0     126.0   
1               1      2    h      S       2.5       1.0  1.0     202.0   
2               2      2    h      S       2.5       1.0  0.0     156.0   
3               3      3    u     VB       2.5       2.0  1.0       0.0   
4               4      3    h     SP       2.5       2.0  0.0     134.0   
...           ...    ...  ...    ...       ...       ...  ...       ...   
34852       34852      4    h     PI       6.3       1.0  3.0     593.0   
34853       34853      2    h     SP       6.3       2.0  1.0      98.0   
34854       34854      2    t      S       6.3       1.0  2.0     220.0   
34855       34855      3    h     SP       6.3       NaN  NaN       NaN   
34856       34856      2    h     PI       6.3       1.0  0.0     250.0   

       BuildingArea             RegionName  PropertyCount      Price    Age  
0               NaN  Northern Metropolitan         4019.0        NaN    NaN  
1               NaN  Northern Metropolitan         4019.0  1480000.0    NaN  
2              79.0  Northern Metropolitan         4019.0  1035000.0  119.0  
3               NaN  Northern Metropolitan         4019.0        NaN    NaN  
4             150.0  Northern Metropolitan         4019.0  1465000.0  119.0  
...             ...                    ...            ...        ...    ...  
34852           NaN   Western Metropolitan         6543.0  1480000.0    NaN  
34853         104.0   Western Metropolitan         6543.0   888000.0    1.0  
34854         120.0   Western Metropolitan         6543.0   705000.0   19.0  
34855           NaN   Western Metropolitan         6543.0  1140000.0    NaN  
34856         103.0   Western Metropolitan         6543.0  1020000.0   89.0  

[34857 rows x 13 columns]

In [41]:
df.shape

(34857, 13)

In [42]:
df.info

<bound method DataFrame.info of        Unnamed: 0  Rooms Type Method  Distance  Bathroom  Car  Landsize  \
0               0      2    h     SS       2.5       1.0  1.0     126.0   
1               1      2    h      S       2.5       1.0  1.0     202.0   
2               2      2    h      S       2.5       1.0  0.0     156.0   
3               3      3    u     VB       2.5       2.0  1.0       0.0   
4               4      3    h     SP       2.5       2.0  0.0     134.0   
...           ...    ...  ...    ...       ...       ...  ...       ...   
34852       34852      4    h     PI       6.3       1.0  3.0     593.0   
34853       34853      2    h     SP       6.3       2.0  1.0      98.0   
34854       34854      2    t      S       6.3       1.0  2.0     220.0   
34855       34855      3    h     SP       6.3       NaN  NaN       NaN   
34856       34856      2    h     PI       6.3       1.0  0.0     250.0   

       BuildingArea             RegionName  PropertyCount      Pric

In [43]:
df.corr()

Unnamed: 0     Rooms  Distance  Bathroom       Car  Landsize  \
Unnamed: 0       1.000000  0.088396  0.259069  0.109118  0.168976  0.029743   
Rooms            0.088396  1.000000  0.271511  0.611826  0.393878  0.037402   
Distance         0.259069  0.271511  1.000000  0.126201  0.241835  0.060862   
Bathroom         0.109118  0.611826  0.126201  1.000000  0.307518  0.036333   
Car              0.168976  0.393878  0.241835  0.307518  1.000000  0.037829   
Landsize         0.029743  0.037402  0.060862  0.036333  0.037829  1.000000   
BuildingArea     0.026642  0.156229  0.076301  0.147558  0.104373  0.354530   
PropertyCount    0.022456 -0.071677 -0.018140 -0.032887 -0.009617 -0.018195   
Price           -0.045098  0.465238 -0.211384  0.429878  0.201803  0.032748   
Age             -0.095326  0.012749 -0.323059 -0.167955 -0.128702 -0.044474   

               BuildingArea  PropertyCount     Price       Age  
Unnamed: 0         0.026642       0.022456 -0.045098 -0.095326  
Rooms              0.156229      -0.071677  0.465238  0.012749  
Distance           0.076301      -0.018140 -0.211384 -0.323059  
Bathroom           0.147558      -0.032887  0.429878 -0.167955  
Car                0.104373      -0.009617  0.201803 -0.128702  
Landsize           0.354530      -0.018195  0.032748 -0.044474  
BuildingArea       1.000000      -0.024523  0.100754 -0.067811  
PropertyCount     -0.024523       1.000000 -0.059017 -0.022420  
Price              0.100754      -0.059017  1.000000  0.333306  
Age               -0.067811      -0.022420  0.333306  1.000000

In [44]:
df.dropna(inplace = True)
df.shape

(8895, 13)

In [45]:
df.isnull().sum()

Unnamed: 0       0
Rooms            0
Type             0
Method           0
Distance         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
RegionName       0
PropertyCount    0
Price            0
Age              0
dtype: int64

In [46]:
y = df[["Price"]]
y

Price
2      1035000.0
4      1465000.0
6      1600000.0
11     1876000.0
14     1636000.0
...          ...
34847   500000.0
34849   570000.0
34853   888000.0
34854   705000.0
34856  1020000.0

[8895 rows x 1 columns]

In [47]:
x = df[["Rooms","Bathroom"]]
x

Rooms  Bathroom
2          2       1.0
4          3       2.0
6          4       1.0
11         3       2.0
14         2       1.0
...      ...       ...
34847      3       2.0
34849      3       2.0
34853      2       2.0
34854      2       1.0
34856      2       1.0

[8895 rows x 2 columns]

In [60]:
#reg = linear_model.LinearRegression(x,y)
#reg.fit(x,y)

In [62]:
reg = linear_model.LinearRegression()

In [63]:
reg.fit(x,y)

LinearRegression()

In [70]:
reg.predict([[2,1]])

array([[690425.6237515]])

In [71]:
reg.intercept_

array([4087.88931665])

In [75]:
reg.coef_

array([[214536.29869297, 257265.13704892]])

In [76]:
# y = m*x + b
2*214536.29869297+1*257265.13704892+4087.88931665

690425.62375151