In [63]:
import pandas as pd
import matplotlib.pyplot
from sklearn import linear_model
import numpy as np

In [64]:
df = pd.read_csv('insurance.csv')

In [65]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [66]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [67]:
df[['age']].min()

age    18
dtype: int64

In [68]:
df[['age']].max()

age    64
dtype: int64

In [69]:
df.loc[1,"sex"]

'male'

In [70]:
df.shape

(1338, 7)

In [71]:
count_f = 0
count_m = 0
for a in df.index:
    if df.loc[a,'sex']=='female':
        count_f = count_f + 1
    else:
        count_m = count_m + 1
print("Female: ",count_f)
print("Male: ",count_m)

Female:  662
Male:  676


In [72]:
for a in df.index:
    if df.loc[a,'sex']=='female':
        df.loc[a,'sex']=0
    else:
        df.loc[a,'sex']=1

In [73]:
# Checking the unique values

In [74]:
df.smoker.unique()

array(['yes', 'no'], dtype=object)

In [75]:
df.region.unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [76]:
for a in df.index:
    if df.loc[a,'smoker']=='no':
        df.loc[a,'smoker']=0
    else:
        df.loc[a,'smoker']=1

In [77]:
df.smoker.unique()

array([1, 0], dtype=object)

In [80]:
for a in df.index:
    if df.loc[a,'region']=='southwest':
        df.loc[a,'region']=0
    if df.loc[a,'region']=='southeast':
        df.loc[a,'region']=1
    if df.loc[a,'region']=='northwest':
        df.loc[a,'region']=2
    if df.loc[a,'region']=='northeast':
        df.loc[a,'region']=3

In [81]:
df.region.unique()

array([0, 1, 2, 3], dtype=object)

In [83]:
df.head()

age sex     bmi  children smoker region      charges
0   19   0  27.900         0      1      0  16884.92400
1   18   1  33.770         1      0      1   1725.55230
2   28   1  33.000         3      0      1   4449.46200
3   33   1  22.705         0      0      2  21984.47061
4   32   1  28.880         0      0      2   3866.85520

In [84]:
df.corr()

age       bmi  children   charges
age       1.000000  0.109272  0.042469  0.299008
bmi       0.109272  1.000000  0.012759  0.198341
children  0.042469  0.012759  1.000000  0.067998
charges   0.299008  0.198341  0.067998  1.000000

In [92]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [96]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [98]:
df.duplicated().sum()

1

In [99]:
df = df.drop_duplicates()

In [101]:
df.duplicated().sum()

0

In [105]:
df.shape

(1337, 7)

In [102]:
x = df[['age','sex','bmi','children','smoker','region']]

In [103]:
y = df[['charges']]

In [104]:
model = linear_model.LinearRegression()

In [106]:
model.fit(x,y)

LinearRegression()

In [107]:
model.predict([[20,0,70,1,0,0]])

array([[16031.05353341]])