In [1]:
type(10)

int

In [2]:
type('Asif Ali')

str

In [4]:
type("Asif Ali")

str

In [5]:
abs(4.567)

4.567

In [6]:
abs(4.567899921)

4.567899921

In [9]:
# Used for finding divider and quotient
divmod(40,3)

(13, 1)

In [11]:
import math

In [13]:
math.sqrt(25)

5.0

In [14]:
from math import sqrt, pow

In [15]:
pow(9,2)

81.0

In [16]:
pow(2,9)

512.0

In [17]:
# Sum of two numbers
x = input("Enter first value1 :")
num1 = int(x)

Enter first value1 :35


In [18]:
y = input("Enter second value :")
num2 = int(y)

Enter second value :45


In [19]:
sum = num1 + num2

In [20]:
sum

80

In [21]:
x = 25
if x%2==0:
    print("Even")
else:
    print("Odd")

Odd


In [25]:
# Elseif
x = -25
if x>=1:
    print("Positive Integer")
elif x%2==0 and x>=1:
    print("Positive Even Integer")
elif x%2!=0 and x>=1:
    print("Positive Odd Integer")
else:
    print("Number is not positive integer")

Number is not positive integer


In [28]:
#For Loop
nums = [1,2,3,4,5]
name = "Python"
for i in name:
    if i=='t':
        break
    print(i)

P
y


In [30]:
#for ... (start, condition, inc/dec)
for i in range (10,0,-2):
    print(i)

10
8
6
4
2


In [39]:
i = 1
while i<=10:
    #print("I="+str(i))
    print("%s%s" % ("I=", i))
  #  print(" {} {}".format("I= ",i))
    i = i+1

I=1
I=2
I=3
I=4
I=5
I=6
I=7
I=8
I=9
I=10


In [69]:
#Nested Loop
for i in range(5):
    for j in range(5):
        print("#", end = " ")
    print()

# # # # # 
# # # # # 
# # # # # 
# # # # # 
# # # # # 


In [81]:
# Triangle
#for i in range(1,5,1):
 #   print("*")
  #  print(end = "")

In [94]:
# List
my_list = [12,14,6]
my_list[1:3]

[14, 6]

In [95]:
min(my_list)

6

In [96]:
max(my_list)

14

In [97]:
my_list.sort()
my_list

[6, 12, 14]

In [103]:
for i in (2,1,0):
    print(my_list[i])

14
12
6


In [104]:
# Sorting list in reverse Order
my_list

[6, 12, 14]

In [110]:
my_list.sort(reverse=True)
my_list

[14, 12, 6]

In [114]:
my_list[2]="Asif"

In [116]:
my_list

[14, 12, 'Asif']

# Tuple

In [111]:
my_tuple = (2,3)
my_tuple

(2, 3)

In [112]:
type(my_tuple)

tuple

# Set

In [124]:
# It will automatically sorted the elements present in the set
my_set = {3,66,1,100}
my_set

{1, 3, 66, 100}

In [125]:
my_list = [2,4,6,8]

In [126]:
my_set.update(my_list)

In [128]:
print("Update set after adding list elements : ",my_set)

Update set after adding list elements :  {1, 2, 66, 3, 100, 4, 6, 8}


# Lists Versus Set

In [134]:
my_string = "Hello my name is Asif Ali"

In [135]:
print(list(my_string))

['H', 'e', 'l', 'l', 'o', ' ', 'm', 'y', ' ', 'n', 'a', 'm', 'e', ' ', 'i', 's', ' ', 'A', 's', 'i', 'f', ' ', 'A', 'l', 'i']


In [136]:
print(set(my_string))

{'o', 'f', 'a', 'H', 'i', ' ', 's', 'e', 'm', 'A', 'n', 'y', 'l'}


# Dictionary 

In [138]:
my_dictionary = {"Brand":"Honda Civic",
                "model": 2020,
                "mileage": "200/h"}

In [139]:
my_dictionary

{'Brand': 'Honda Civic', 'model': 2020, 'mileage': '200/h'}

In [142]:
for a in my_dictionary:
    print(a)

Brand
model
mileage


# Arrays in Python

In [144]:
from array import *

In [163]:
my_array = array('i',[2,3,1,4,5])

In [164]:
print(my_array[1])

3


In [165]:
my_array.index(1)

2

In [166]:
# Counting the elements in the array
my_array.count(2)

1

In [167]:
my_array.count(10)

0

In [168]:
my_array.buffer_info()

(1751004675440, 5)

In [169]:
my_array.reverse()

In [170]:
my_array

array('i', [5, 4, 1, 3, 2])

In [171]:
# Slicing an array

In [172]:
my_array[2:4]

array('i', [1, 3])

In [181]:
my_array[2:]

array('i', [1, 3, 2])

In [182]:
#Adding two arrays

In [183]:
import array as arr

In [184]:
my_array1 = arr.array('i',[1,3,5])

In [185]:
my_array2 = arr.array('i',[2,4,6])

In [186]:
arrays = arr.array('i')

In [187]:
arrays = my_array1 + my_array2

In [188]:
arrays 

array('i', [1, 3, 5, 2, 4, 6])

# Numpy

In [190]:
import numpy as np

In [198]:
arr = np.array([1,2,3,4])
# Creating an array by passing a list inside

In [192]:
arr

array([1, 2, 3, 4])

In [193]:
np.__version__

'1.18.5'

In [199]:
arr = np.array((1,2,3,4))
# Creating an array by passing a tuple inside
arr

array([1, 2, 3, 4])

In [201]:
# 0 Dimensional Array
arr0 = np.array(20)
arr0

array(20)

In [204]:
#Dimension
print("Dimension: ",arr0.ndim)

Dimension:  0


In [240]:
# 1 Dimensional Array
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [241]:
#Checking Dimension
print("Dimension: ",arr1.ndim)

Dimension:  1


In [242]:
#2 Dimnesional Array
arr2 = np.array([[1,3,5],[2,4,6]])
arr2

array([[1, 3, 5],
       [2, 4, 6]])

In [243]:
#Checking Dimension
print("Dimension: ",arr2.ndim)

Dimension:  2


In [244]:
#3 Dimensional Array
arr3 = np.array([[[1,3,5],[2,4,6],[10,20,30],[100,200,300]]])
arr3

array([[[  1,   3,   5],
        [  2,   4,   6],
        [ 10,  20,  30],
        [100, 200, 300]]])

In [245]:
#Checking Dimension
print("Dimension: ",arr3.ndim)

Dimension:  3


In [246]:
#Creating own choice dimensions simply by wrting ndmin = any number

In [247]:
arr5 = np.array([1,2,3,4,5],ndmin=5)
arr5

array([[[[[1, 2, 3, 4, 5]]]]])

In [248]:
print("Dimension: ",arr5.ndim)

Dimension:  5


In [249]:
#Accessing elements using indexes in Two dimensional array

In [250]:
my_arrays =np.array([[1,2,3],[4,5,6]])
print(my_arrays[0,-1])

3


In [251]:
#Accessing elements using indexes in Three Dimensional Array

In [252]:
my_arrays = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(my_arrays[0,1,-1])

6


In [253]:
# Get the shape of the array

In [254]:
my_arrays.shape

(1, 3, 3)

In [255]:
arr2.shape

(2, 3)

In [256]:
arr3.shape

(1, 4, 3)

In [257]:
arr1.shape

(4,)

In [265]:
arr1

array([1, 2, 3, 4])

In [268]:
newarr = arr1.reshape(2,2)
newarr

array([[1, 2],
       [3, 4]])

In [269]:
arr2

array([[1, 3, 5],
       [2, 4, 6]])

In [270]:
arr2.shape

(2, 3)

In [272]:
newarr = arr2.reshape(3,2)
newarr

array([[1, 3],
       [5, 2],
       [4, 6]])

In [275]:
# Array Iterating

In [276]:
for i in arr2:
    for j in i:
        print(j)

1
3
5
2
4
6


In [277]:
arr3

array([[[  1,   3,   5],
        [  2,   4,   6],
        [ 10,  20,  30],
        [100, 200, 300]]])

In [279]:
for i in arr3:
    for j in i:
        for k in j:
            print(k)

1
3
5
2
4
6
10
20
30
100
200
300


In [280]:
# Iterating array using nditer()

In [281]:
arr3

array([[[  1,   3,   5],
        [  2,   4,   6],
        [ 10,  20,  30],
        [100, 200, 300]]])

In [282]:
for a in np.nditer(arr3):
    print(a)

1
3
5
2
4
6
10
20
30
100
200
300


In [283]:
# Numpy Array spiliting

In [290]:
arr2 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])

In [292]:
arr2.shape

(6, 2)

In [294]:
newarr = np.array(np.array_split(arr2,3))
newarr.shape

(3, 2, 2)

In [295]:
newarr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [297]:
data = np.array([[11,22,33],[44,55,66],[77,88,99]])
split = 2
train,test = data[:split,:], data[split:,:]
train

array([[11, 22, 33],
       [44, 55, 66]])

In [298]:
test

array([[77, 88, 99]])

In [299]:
data.shape

(3, 3)