In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('Homeprices.csv')

In [3]:
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [19]:
model =linear_model.LinearRegression()

In [20]:
model.fit(df[["area"]],df[["price"]])

LinearRegression()

In [21]:
model.predict([[2000]])

array([[452191.78082192]])

In [22]:
model.coef_

array([[135.78767123]])

In [23]:
model.intercept_

array([180616.43835616])

In [14]:
# y = m*x + b
135.78767123*2000+180616.43835616

452191.78081616

In [15]:
# Want to train the model and save it and also we can test it without training angain

In [24]:
import pickle

In [25]:
with open('model_pickle','wb') as f:
    pickle.dump(model,f)

In [27]:
with open('model_pickle','rb') as f:
    m = pickle.load(f)

In [28]:
m.predict([[2000]])

array([[452191.78082192]])

In [33]:
import joblib

In [38]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [39]:
mj = joblib.load('model_joblib')

In [40]:
mj.predict([[2000]])

array([[452191.78082192]])